# Generated by Django 4.1 on 2023-05-10 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageUpload',
            fields=[
                ('author', models.CharField(max_length=150, primary_key=True, serialize=False)),
                ('origin', models.ImageField(upload_to='')),
            ],
        ),
    ]
