# Generated by Django 4.1 on 2023-05-02 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_processing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('author', models.CharField(max_length=150)),
            ],
        ),
    ]
