# Generated by Django 4.1 on 2023-05-02 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_processing', '0002_storesession'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storesession',
            name='author',
            field=models.CharField(max_length=150, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='storesession',
            name='session_key',
            field=models.CharField(max_length=40),
        ),
    ]
