# Generated by Django 4.1 on 2023-04-30 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageUpload',
            fields=[
                ('author', models.CharField(max_length=150, primary_key=True, serialize=False)),
                ('origin', models.ImageField(upload_to='')),
                ('process', models.ImageField(blank=True, null=True, upload_to='')),
                ('types', models.CharField(choices=[('Brightness', 'b'), ('Contrast', 'c'), ('Kmeans', 'k')], max_length=50)),
            ],
        ),
    ]
