# Generated by Django 4.1 on 2023-05-03 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reporter',
            name='blogs_list',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='reporter',
            name='friends_list',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='reporter',
            name='organization',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='reporter',
            name='question_list',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
